#!/usr/bin/env python3

from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter


parser = ArgumentParser(formatter_class=ArgumentDefaultsHelpFormatter)
parser.add_argument("-m", "--mastercode", default="BEEFBEEFBEEF",
                    help="12-digit hex mastercode to enable configuration "
                         "of the FlashAir device (default: %default)")
parser.add_argument("
